services:
  django:
    build: 
      dockerfile: docker/Dockerfile
      context: .
    container_name: django
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./src/mysite:/root/app
    command: python manage.py runserver 0.0.0.0:8000